version: '2'
services:
  eurekaserver:
    image:   tj-ms/tylerjones/tmx-eurekasvr:assgn2_3
    ports:
      - "8761:8761"
  configserver:
    image: tj-ms/tylerjones/tmx-confsvr:assgn2_3
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: "IMSYMMETRIC"
  zuulserver:
    image: tj-ms/tylerjones/tmx-zuulsvr:assgn2_3
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ORGSERVERNEW_PORT:        "8087"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB: "eagle_eye_local"
  assetservice:
    image: tj-ms/tylerjones/tmx-asset-service:assgn2_3
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      CONFIGSERVER_PORT:        "8888"
      DATABASESERVER_PORT:      "5432"
      ORGSERVERNEW_PORT:        "8087"
      ZUULSERVER_PORT:          "5555"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  organizationservice:
    image: tj-ms/tylerjones/tmx-organization-service:assgn2_3
    ports:
      - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      CONFIGSERVER_PORT:        "8888"
      DATABASESERVER_PORT:      "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  orgservice-new:
    image: tj-ms/tylerjones/tmx-orgservice-new:assgn2_3
    ports:
      - "8087:8087"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8087"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  specialroutes-service:
    image: tj-ms/tylerjones/tmx-specialroutes-service:assgn2_3
    ports:
      - "8910:8910"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8910"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ENCRYPT_KEY:       "IMSYMMETRIC"
